version: '3.8'
services:
  app:
    build: .
    container_name: noo-b-ooking
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn main:app --host 0.0.0.0'
    volumes:
      - "./:/code/app"
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - "/pgdata:/var/lib/postgresql/data"
    env_file:
      - .env
volumes:
  pgdata:
