"""add relationship reservation

Revision ID: 6b8ff98be166
Revises: c890bfba4b37
Create Date: 2023-05-15 12:02:00.047903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b8ff98be166'
down_revision = 'c890bfba4b37'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'property', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'property', type_='foreignkey')
    op.drop_column('property', 'owner_id')
    # ### end Alembic commands ###
