"""second init

Revision ID: 7447e39a9b85
Revises: 514addcb9b5f
Create Date: 2023-05-11 14:13:06.677354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7447e39a9b85'
down_revision = '514addcb9b5f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
