"""init user

Revision ID: 983af03a8e1b
Revises: 
Create Date: 2023-05-11 13:57:14.961520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '983af03a8e1b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
