"""reservation model update v 1.0

Revision ID: a9fae4ab0e29
Revises: 446143e03960
Create Date: 2023-05-14 11:54:02.036688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9fae4ab0e29'
down_revision = '446143e03960'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('num_guests', sa.Integer(), nullable=False))
    op.add_column('reservation', sa.Column('start_date', sa.Date(), nullable=False))
    op.add_column('reservation', sa.Column('end_date', sa.Date(), nullable=False))
    op.add_column('reservation', sa.Column('guest_id', sa.Integer(), nullable=True))
    op.add_column('reservation', sa.Column('property_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'reservation', 'user', ['guest_id'], ['id'])
    op.create_foreign_key(None, 'reservation', 'property', ['property_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reservation', type_='foreignkey')
    op.drop_constraint(None, 'reservation', type_='foreignkey')
    op.drop_column('reservation', 'property_id')
    op.drop_column('reservation', 'guest_id')
    op.drop_column('reservation', 'end_date')
    op.drop_column('reservation', 'start_date')
    op.drop_column('reservation', 'num_guests')
    # ### end Alembic commands ###
