"""trying to fix string lenght 2

Revision ID: c890bfba4b37
Revises: aba7fd2ebc69
Create Date: 2023-05-14 12:11:12.988166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c890bfba4b37'
down_revision = 'aba7fd2ebc69'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property', sa.Column('title', sa.String(length=255), nullable=False))
    op.add_column('property', sa.Column('country', sa.String(length=255), nullable=False))
    op.add_column('property', sa.Column('city', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_property_city'), 'property', ['city'], unique=False)
    op.create_index(op.f('ix_property_country'), 'property', ['country'], unique=False)
    op.add_column('user', sa.Column('email', sa.String(length=350), nullable=False))
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_column('user', 'email')
    op.drop_index(op.f('ix_property_country'), table_name='property')
    op.drop_index(op.f('ix_property_city'), table_name='property')
    op.drop_column('property', 'city')
    op.drop_column('property', 'country')
    op.drop_column('property', 'title')
    # ### end Alembic commands ###
