"""reservation model update v 1.1

Revision ID: e04503c03c4c
Revises: a9fae4ab0e29
Create Date: 2023-05-14 11:55:23.519453

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e04503c03c4c'
down_revision = 'a9fae4ab0e29'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('property', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('property', 'type',
               existing_type=postgresql.ENUM('hotel', 'hostel', 'apartment', 'homestay', name='propertytype'),
               nullable=False)
    op.alter_column('property', 'price',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('property', 'price',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('property', 'type',
               existing_type=postgresql.ENUM('hotel', 'hostel', 'apartment', 'homestay', name='propertytype'),
               nullable=True)
    op.alter_column('property', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
